name: Build pdf

on:
  push:
    branches:
      - '**'
    paths:
      - '*/scripts/statement.sh'
      - '*/statement/*.jpg'
      - '*/statement/DISABLE_AUTO_BUILD'
      - '*/statement/index.md'
      - '*/problem.json'
      - '*/subtasks.json'
      - 'template.tex'
      - 'cover.tex'
  workflow_dispatch:
    inputs:
      problems:
        description: 'Problem labels to build (A-Z)'
        default: ''
      merge:
        description: 'Merge pdfs?'
        type: boolean

jobs:
  run:
    uses: TNFSH-Programming-Contest/tps-actions/.github/workflows/build-pdf.yml@main
    with:
      problems: ${{ github.event.inputs.problems }}
      merge: ${{ fromJson(github.event.inputs.merge) }}
      runs-on: self-hosted
