name: List subtasks

on:
  push:
    branches:
      - '**'
    paths:
      - '*/subtasks.json'
  workflow_dispatch:

jobs:
  run:
    uses: XiPlus-Test/tps-actions-test/.github/workflows/list-subtasks.yml@main
